#!/bin/bash

function create_local_debian_repo() {
    mkdir -p /tmp/pkgs
    cp /mnt/pkgs/*.deb /tmp/pkgs
    pushd /tmp/pkgs
    dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
    popd
    echo "deb [trusted=yes] file:/tmp/pkgs /" > \
	 /etc/apt/sources.list.d/001local.list
    cat > /etc/apt/preferences.d/001local.pref << EOF
Package: *
Pin: origin ""
Pin-Priority: 999
EOF
    
}

function pin_danos_repos() {
    cat > /etc/apt/preferences.d/998danos << EOF
Package: *
Pin: release o=DANOS
Pin-Priority: 998
EOF
    
}

function setup_apt() {
    create_local_debian_repo
    pin_danos_repos
    apt-get update
}

function import_source() {
    cp -a /mnt/src /build/src
    chown -R builduser:builduser /build/
}

function install_build_dependencies() {
    apt-get -y install base-files-vyatta lintian-profile-vyatta
    mk-build-deps --install --remove --tool \
		  "apt-get -o Debug::pkgProblemResolver=yes \
	      	       --no-install-recommends -y" \
		  debian/control
}

function build_package() {
    local gbp_args="--git-verbose \
	--git-ignore-branch \
	--git-ignore-new \
	--git-export-dir=.."
    local dpkg_args="-us -uc -i -b"

    if git rev-parse --verify --quiet origin/pristine-tar>/dev/null ; then
	git branch pristine-tar origin/pristine-tar
    else
	gbp_args="$gbp_args --git-no-pristine-tar"
    fi

    local cmd="gbp buildpackage $gbp_args $dpkg_args"
    echo "$cmd"
    su builduser -c "$cmd"
}

function export_package() {
    chmod 666 ../*.deb
    cp ../*.deb /mnt/output
}

export DEBIAN_FRONTEND=noninteractive
setup_apt
import_source || exit 1

pushd /build/src
install_build_dependencies || exit 1
build_package || exit 1
export_package
popd
