#!/bin/bash

function create_local_debian_repo() {
    mkdir -p /tmp/pkgs
    cp /mnt/pkgs/*.deb /tmp/pkgs
    pushd /tmp/pkgs
    dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
    popd
    echo "deb [trusted=yes] file:/tmp/pkgs /" > \
	 /etc/apt/sources.list.d/001local.list
    cat > /etc/apt/preferences.d/001local.pref << EOF
Package: *
Pin: origin ""
Pin-Priority: 999
EOF

    apt-get update
}

function import_source() {
    cp -a /mnt/src /build/
    chown -R builduser:builduser /build/
}

function install_build_dependencies() {
    apt-get -y install base-files-vyatta lintian-profile-vyatta lintian
    mk-build-deps --install --remove --tool \
		  "apt-get -o Debug::pkgProblemResolver=yes \
	      	       --no-install-recommends -y" \
		  debian/control
}

function build_package() {
    su builduser -c "debuild -uc -us -i -b"
}

function export_package() {
    chmod 666 ../*.deb
    cp ../*.deb /mnt/output
}

export DEBIAN_FRONTEND=noninteractive
create_local_debian_repo
import_source || exit 1
install_build_dependencies || exit 1
build_package || exit 1
export_package
